### ISSUE TITLE
When the curtain cannot go all the way down, the curtain close button (down) has no effect.

### ISSUE THREAD

**Issue by haigaru** [Sese-Schneider/ha-cover-time-based#11]
While using RF controlled curtains, the signal is missed and cannot be closed. I want to close the curtain with the down navigation button but it doesn't work.

**Comment by Sese-Schneider** [comment]
Unfortunately this issue can't be solved IMO. The whole point of this integration is to allow for control with an assumed internal state. When the assumed internal state is "all the way down", clicking on down should have no effect ...
The buttons in HA are technically the same as using the slider.
