### ISSUE TITLE
Update state of cover when use physical switch

### ISSUE THREAD

**Issue by brunopiras** [Sese-Schneider/ha-cover-time-based#16]
Hi,

Would it be possible to make it so that when I use the physical buttons to raise or lower it also updates the status of the cover on ha?

Thanks

**Comment by brunopiras** [comment]
Duplicate, I'm sorry!!

**Comment by Sese-Schneider** [comment]
[yes](https://github.com/Sese-Schneider/ha-cover-time-based/issues/6), dw. I hope I can build this soon
