### ISSUE TITLE
Use different entities

### ISSUE THREAD

**Issue by Guenni9** [Sese-Schneider/ha-cover-time-based#3]
Dear @Sese-Schneider,

I'm using a Logo!8 with my blinds. Via NodeRed-S7-contrib I'm able to communicate with home assistant. The blinds are controlled by hardware buttons, storm-sensor and astro-clock in the Logo.

Is there a chance to use different entities as inputs to control and other entities for the state?
In my case, Logo inputs I1/2 is the up down button, outputs Q1/2 is the motor.

So, I would be able to see the state of the blinds, even when triggered by other hardware input commands to my Logo.

Thank you and have a nice day!

**Comment by Sese-Schneider** [comment]
Hi @Guenni9 

If I understand correctly, you want to have the ability to update the internal state of the blind position via e.g. a service?
Or do you simply want to control the blinds with the inputs?

You could already do that!
This integration supports all the service commands to `cover.<id>`. So you could write an automation which triggers those services based on your inputs.

For example to open it you can call this service:
```yaml
service: cover.open_cover
target:
  entity_id:
    - cover.room_rolling_shutter
data: {}
```

Does this solve your problem?
