### ISSUE TITLE
Entities not available in latest version

### ISSUE THREAD

**Issue by julianmueller** [Sese-Schneider/ha-cover-time-based#8]
Since the latest update from 2.0.1 -> 2.1.0, my entities stopped working, as they are not available anymore. I did not change the YAML config or anything else. Once I downgraded, everything is back to normal.

**Comment by Sese-Schneider** [comment]
@julianmueller can you please share your configuration?

**Comment by Sese-Schneider** [comment]
Thank you for your report. The issue is fixed in `v2.1.1` @julianmueller
